"""ORBIT — Oral Radiology Board-Interpretation Trainer.

A Flask curriculum console for the Dr. Perelman AIxEducation dental-radiology
project, styled after the Epic clinical dashboard. Content is loaded from
`data/orbit.json` (generated by `build_data.py`). Module 4 is a fully
functioning, demo-able learning module (see `/module/4/practice`).

Run:
    pip install -r requirements.txt
    python build_data.py          # (re)generate data/orbit.json from the .xlsx
    python app.py                 # serves http://127.0.0.1:5001
"""

from __future__ import annotations

import json
import os
import re
from pathlib import Path

from flask import Flask, abort, jsonify, render_template, request, url_for

HERE = Path(__file__).resolve().parent
DATA_FILE = HERE / "data" / "orbit.json"
MODULE4_FILE = HERE / "data" / "module4_cases.json"
MODULE1_FILE = HERE / "data" / "module1_cases.json"

DIFFICULTY = {
    1: {"label": "Obvious / basic", "short": "Basic", "cls": "diff1"},
    2: {"label": "Moderate", "short": "Moderate", "cls": "diff2"},
    3: {"label": "Subtle / complex", "short": "Complex", "cls": "diff3"},
}


def load_json(path: Path) -> dict:
    if not path.exists():
        raise SystemExit(f"{path.name} is missing — run `python build_data.py` first.")
    with open(path, encoding="utf-8") as f:
        return json.load(f)


DATA = load_json(DATA_FILE)
MODULES = DATA["modules"]
CASES = DATA["cases"]
BUILDOUT = DATA["buildout"]
MODULE4 = load_json(MODULE4_FILE)
MODULE1 = load_json(MODULE1_FILE)

MODULES_BY_NUM = {m["number"]: m for m in MODULES}
CASES_BY_ID = {c["id"]: c for c in CASES}
M4_BY_ID = {c["id"]: c for c in MODULE4["cases"]}

# Modules that have a functioning interactive trainer -> its route endpoint.
PRACTICE_ENDPOINTS = {1: "module1_practice", 4: "module4_practice"}

app = Flask(__name__)


# ---------------------------------------------------------------------------
# Anthropic key resolution (env first, then the project's Streamlit secrets)
# ---------------------------------------------------------------------------
def anthropic_key() -> str:
    key = os.environ.get("ANTHROPIC_API_KEY", "").strip()
    if key:
        return key
    secrets = HERE.parent / ".streamlit" / "secrets.toml"
    if secrets.exists():
        try:
            m = re.search(r'ANTHROPIC_API_KEY\s*=\s*["\']?([^"\'\n]+)', secrets.read_text())
            if m:
                return m.group(1).strip()
        except Exception:
            pass
    return ""


# ---------------------------------------------------------------------------
# template helpers
# ---------------------------------------------------------------------------
@app.context_processor
def inject_globals():
    return {
        "platform": DATA["platform"],
        "stats": DATA["stats"],
        "nav_modules": MODULES,
        "DIFFICULTY": DIFFICULTY,
        "active": request.path,
    }


@app.template_filter("diff_cls")
def diff_cls(level):
    return DIFFICULTY.get(level, {}).get("cls", "diff0")


@app.template_filter("diff_label")
def diff_label(level):
    return DIFFICULTY.get(level, {}).get("short", "—")


# ---------------------------------------------------------------------------
# routes
# ---------------------------------------------------------------------------
@app.route("/")
def overview():
    recent = sorted(CASES, key=lambda c: (-c.get("steps", 0), c["id"]))[:8]
    return render_template("overview.html", recent_cases=recent, page="overview")


@app.route("/module/<int:number>")
def module(number: int):
    mod = MODULES_BY_NUM.get(number)
    if mod is None:
        abort(404)
    ordered = [m["number"] for m in MODULES]
    idx = ordered.index(number)
    prev_num = ordered[idx - 1] if idx > 0 else None
    next_num = ordered[idx + 1] if idx < len(ordered) - 1 else None
    endpoint = PRACTICE_ENDPOINTS.get(number)
    practice_url = url_for(endpoint) if endpoint else None
    return render_template(
        "module.html", mod=mod, page="modules",
        prev_num=prev_num, next_num=next_num,
        practice_url=practice_url)


@app.route("/module/1/practice")
def module1_practice():
    return render_template("module1_practice.html", page="modules", m1=MODULE1)


@app.route("/module/4/practice")
def module4_practice():
    return render_template("module4_practice.html", page="modules", m4=MODULE4,
                           ai_available=bool(anthropic_key()))


@app.route("/api/module4/tutor", methods=["POST"])
def module4_tutor():
    payload = request.get_json(force=True, silent=True) or {}
    case = M4_BY_ID.get(payload.get("case_id"))
    if case is None:
        return jsonify({"error": "unknown case"}), 404
    student = (payload.get("student_answer") or "").strip()
    history = payload.get("history") or []
    user_msg = (payload.get("message") or "").strip()

    fallback = _scripted_tutor(case, student)
    key = anthropic_key()
    if not key:
        return jsonify({"reply": fallback, "source": "scripted"})

    try:
        from anthropic import Anthropic
        client = Anthropic(api_key=key)
        system = (
            "You are a Socratic dental-radiology tutor helping a student in Module 4: "
            "Normal Anatomy vs Pathology. Your job is to guide, not to lecture.\n\n"
            f"CASE: {case['name']} ({case['id']}).\n"
            f"Radiograph finding: {case['finding']}\n"
            f"Correct classification (do NOT state this outright unless the student is stuck): "
            f"{case['ground_truth']}.\n"
            f"Key radiographic features: {', '.join(case['features'])}.\n"
            f"Why it is a trap: {case['trap']}\n"
            f"Teaching hint: {case['review_hint']}\n\n"
            "Rules: reply in 2-4 sentences. Ask ONE focused guiding question that points the "
            "student to a discriminating radiographic feature (shape, border, location, symmetry, "
            "lamina dura, cortication). Encourage them to reconsider or confirm using evidence. "
            "Never just give the answer on the first turn."
        )
        messages = []
        for h in history[-6:]:
            role = "assistant" if h.get("role") == "assistant" else "user"
            messages.append({"role": role, "content": str(h.get("content", ""))})
        if user_msg:
            messages.append({"role": "user", "content": user_msg})
        elif not messages:
            messages.append({"role": "user",
                             "content": f"I classified this as '{student}'. Am I on the right track?"})

        resp = client.messages.create(
            model="claude-haiku-4-5", max_tokens=320, system=system, messages=messages)
        text = "".join(getattr(b, "text", "") for b in resp.content).strip()
        return jsonify({"reply": text or fallback, "source": "ai" if text else "scripted"})
    except Exception as e:  # graceful degrade — the demo must never break
        return jsonify({"reply": fallback, "source": "scripted", "error": str(e)[:200]})


def _scripted_tutor(case: dict, student: str) -> str:
    lead = (f"You classified this as “{student}.” " if student else "")
    return (f"{lead}Before locking it in, {case['review_hint'][0].lower()}{case['review_hint'][1:]} "
            f"If this were true pathology, what would you expect the border and the surrounding "
            f"bone to look like — and does this finding show that?")


@app.route("/cases")
def cases():
    f_module = request.args.get("module", type=int)
    f_diff = request.args.get("difficulty", type=int)
    f_type = request.args.get("type", default="", type=str)

    rows = CASES
    if f_module:
        rows = [c for c in rows if c["module"] == f_module]
    if f_diff:
        rows = [c for c in rows if c["difficulty"] == f_diff]
    if f_type:
        rows = [c for c in rows if c["type"] == f_type]

    case_types = sorted({c["type"] for c in CASES if c["type"]})
    modules_with_cases = sorted({c["module"] for c in CASES
                                 if isinstance(c["module"], int)})
    return render_template(
        "cases.html", page="cases", rows=rows,
        case_types=case_types, modules_with_cases=modules_with_cases,
        f_module=f_module, f_diff=f_diff, f_type=f_type,
        total=len(CASES))


@app.route("/case/<case_id>")
def case(case_id: str):
    c = CASES_BY_ID.get(case_id)
    if c is None:
        abort(404)
    steps = BUILDOUT["by_case"].get(case_id, [])
    mod = MODULES_BY_NUM.get(c["module"]) if isinstance(c["module"], int) else None
    total_points = sum(s.get("points", 0) for s in steps)
    return render_template(
        "case.html", page="cases", c=c, steps=steps, mod=mod,
        total_points=total_points)


@app.route("/interaction")
def interaction():
    rows = DATA.get("interaction") or []
    if not rows:
        rows = [r for m in MODULES for r in m.get("interaction", [])]
    return render_template("interaction.html", page="interaction",
                           rows=rows, modules=MODULES)


@app.route("/reference")
def reference():
    return render_template("reference.html", page="reference",
                           reference=DATA["reference"])


@app.route("/api/data")
def api_data():
    return DATA


@app.route("/healthz")
def healthz():
    return {"ok": True, "modules": len(MODULES), "cases": len(CASES),
            "ai_tutor": bool(anthropic_key())}


@app.errorhandler(404)
def not_found(_e):
    return render_template("404.html"), 404


if __name__ == "__main__":
    app.run(host="127.0.0.1", port=5001, debug=True)
